# Generated by Django 5.1.6 on 2025-02-16 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_quizid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quizId',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quiz'),
        ),
    ]
