# Generated by Django 5.1.6 on 2025-02-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_quizid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quizId',
            field=models.IntegerField(default=0),
        ),
    ]
