# Generated by Django 5.1.6 on 2025-02-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=25)),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=25)),
            ],
        ),
    ]
