# Generated by Django 5.1.6 on 2025-02-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=25)),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=25)),
                ('qr_code', models.ImageField(default='NULL', upload_to='./map/static')),
                ('qr_code_message', models.CharField(default='NULL', max_length=50)),
                ('task', models.CharField(default='NULL', max_length=20)),
                ('quizId', models.IntegerField(default=0)),

            ],
        ),
    ]
