# Generated by Django 5.1.6 on 2025-02-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='qr_code',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
