# Generated by Django 5.1.6 on 2025-02-16 18:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='quizId',
            new_name='challengeId',
        ),
    ]
