# Generated by Django 5.1.6 on 2025-02-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_location_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='qr_code',
            field=models.ImageField(default='NULL', upload_to='./static'),
        ),
    ]
