# Generated by Django 5.1.6 on 2025-03-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_remove_location_task_alter_location_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='qr_code_message',
            new_name='icon',
        ),
        migrations.RemoveField(
            model_name='location',
            name='challengeId',
        ),
        migrations.RemoveField(
            model_name='location',
            name='qr_code',
        ),
    ]
