# Generated by Django 5.1.6 on 2025-02-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_location_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='qr_code_message',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
