# Generated by Django 5.1.6 on 2025-02-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_location_qr_code_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='task',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
