# Generated by Django 5.1.6 on 2025-02-15 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challengeId', models.BigAutoField(primary_key=True, serialize=False)),
                ('challenge', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField()),
                ('challengeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userprofile')),
            ],
        ),
    ]
