# Generated by Django 5.1.6 on 2025-02-16 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('is_user', models.BooleanField(default=1)),
                ('is_developer', models.BooleanField(default=0)),
                ('is_admin', models.BooleanField(default=0)),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
