name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Registration Tests
      run: |
        python groupproject/manage.py migrate registration
        python groupproject/manage.py test registration
    - name: Run Login Tests
      run: |
        python groupproject/manage.py migrate login
        python groupproject/manage.py test login
    - name: Run Map Tests
      run: |
        python groupproject/manage.py migrate map
        python groupproject/manage.py test map
